### ISSUE TITLE
add the possibility to change the price also

### ISSUE THREAD

**Issue by omarherri** [CodyHouse/cd-product-v2-changelog#1]
Hi, in some websites when we switch the color the price also change cause in some cases the price depends on the variation of product.
Is there a way to shift this feature??

**Comment by claudia-romano** [comment]
Hi there, I see your point. 
Multiple info may need to be updated when a new color is selected (price, available sizes, etc). We did not implement that as this is strongly dependent on the store. But you can listen to the change of color and update your product info accordingly. This is how you could do that:
```js
var productV2 = document.getElementsByClassName('js-product-v2');
if(productV2.length > 0) {
  var colorSwatches = productV2[0].getElementsByClassName('js-color-swatches__select');

  colorSwatches[0].addEventListener('change', function(event){
    // color has been changed
    // colorSwatches[0].options[colorSwatches[0].selectedIndex].value is the new selected color value
    // make all the changes you need to your product info
  });
}
```

This should solve your problem. Cheers!

**Comment by omarherri** [comment]
okayy thank you for your reply. I'll implement your solution.
