### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by erikvanberkum** [CodyHouse/cd-product-v2-changelog#2]
On the website
https://codyhouse.co/ds/components/app/product-v2

If you're using this component, you should include the SCSS/JS of the following components:

8 dependencies are shown, number 9: the column oriented table is missing.

https://codyhouse.co/ds/components/app/column-oriented-table

**Comment by sebastiano-guerriero** [comment]
Hi Erik, we're using the column oriented table in our [Mercurio template](https://codyhouse.co/demo-templates/mercurio/product-v1.html), but it's not a required dependency if you're using the Product v2 component.

**Comment by erikvanberkum** [comment]
Sorry, I am indeed working of the Mercurio template

**Comment by sebastiano-guerriero** [comment]
no prob 👍
